# Generated by Django 4.1.1 on 2022-10-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUserField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('playing_field', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='created_at',
            new_name='last_phase_start',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
