# Generated by Django 4.1.1 on 2022-10-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_game_dice_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuserfield',
            name='potential_moves',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
