# Generated by Django 4.1.1 on 2022-10-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_gameuserfield_potential_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuserfield',
            name='potential_moves',
        ),
    ]
