# Generated by Django 4.1.1 on 2022-10-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_remove_gameuserfield_potential_moves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='dice_rolls',
            new_name='route_rolls',
        ),
    ]
