# Generated by Django 4.1.1 on 2022-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_rename_dice_rolls_game_route_rolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='phase',
        ),
        migrations.AddField(
            model_name='gameuserfield',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
