# Generated by Django 4.1.1 on 2022-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_gameuserfield_center_score_gameuserfield_exit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
