# Generated by Django 4.1.1 on 2022-11-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_game_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
