# Generated by Django 4.1.1 on 2022-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0010_game_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_count',
            field=models.IntegerField(default=0),
        ),
    ]
