# Generated by Django 4.1.1 on 2022-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0011_game_players_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_private',
            field=models.BooleanField(default=0),
        ),
    ]
