# Generated by Django 4.1.1 on 2022-11-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0012_game_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_phase_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
