# Generated by Django 4.1.1 on 2022-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0013_alter_game_last_phase_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_phase_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
