# Generated by Django 4.1.1 on 2022-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0014_alter_game_last_phase_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuserfield',
            name='game_over',
            field=models.BooleanField(default=0),
        ),
    ]
